### ISSUE TITLE
ERROR: Service 'web' failed to build: The command '/bin/sh -c pip install mysql' returned a non-zero code: 1

### ISSUE THREAD

**Issue by gopalkotlanka** [valhallasw/virtual-mysql-pypi-package#2]
in a docker-compose.yaml file i tried to execute the below code
RUN pip install mysql and it returned me with the below error
Collecting mysql
  Downloading mysql-0.0.2.tar.gz (1.9 kB)
    ERROR: Command errored out with exit status 1:
     command: /usr/local/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-_pzkjq73/mysql_8fa60f6088694a049c34763c9b511fe7/setup.py'"'"'; __file__='"'"'/tmp/pip-install-_pzkjq73/mysql_8fa60f6088694a049c34763c9b511fe7/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-tg3ghml4
         cwd: /tmp/pip-install-_pzkjq73/mysql_8fa60f6088694a049c34763c9b511fe7/
    Complete output (28 lines):
    WARNING: `mysql` is a virtual package. Please use `%s` as a dependency directly.
    
    running egg_info
    creating /tmp/pip-pip-egg-info-tg3ghml4/mysql.egg-info
    writing /tmp/pip-pip-egg-info-tg3ghml4/mysql.egg-info/PKG-INFO
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-_pzkjq73/mysql_8fa60f6088694a049c34763c9b511fe7/setup.py", line 33, in <module>
        setup(
      File "/usr/local/lib/python3.9/site-packages/setuptools/__init__.py", line 153, in setup
        return distutils.core.setup(**attrs)
      File "/usr/local/lib/python3.9/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/local/lib/python3.9/distutils/dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "/usr/local/lib/python3.9/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/usr/local/lib/python3.9/site-packages/setuptools/command/egg_info.py", line 292, in run
        writer(self, ep.name, os.path.join(self.egg_info, ep.name))
      File "/usr/local/lib/python3.9/site-packages/setuptools/command/egg_info.py", line 628, in write_pkg_info
        metadata.write_pkg_info(cmd.egg_info)
      File "/usr/local/lib/python3.9/distutils/dist.py", line 1117, in write_pkg_info
        self.write_pkg_file(pkg_info)
      File "/usr/local/lib/python3.9/site-packages/setuptools/dist.py", line 172, in write_pkg_file
        license = rfc822_escape(self.get_license())
      File "/usr/local/lib/python3.9/distutils/util.py", line 476, in rfc822_escape
        lines = header.split('\n')
    AttributeError: 'list' object has no attribute 'split'
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/bf/5f/b574ac9f70811df0540e403309f349a8b9fa1a25d3653824c32e52cc1f28/mysql-0.0.2.tar.gz#sha256=55e66b5e7b3823b1da5fb2a063e95a628fb850b2a0b76bdcd884faac5d2daa7d (from https://pypi.org/simple/mysql/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  Downloading mysql-0.0.1.tar.gz (1.7 kB)
    ERROR: Command errored out with exit status 1:
     command: /usr/local/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-_pzkjq73/mysql_02f1e1ca9632450ea6329469549864cf/setup.py'"'"'; __file__='"'"'/tmp/pip-install-_pzkjq73/mysql_02f1e1ca9632450ea6329469549864cf/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-6lw2mkwl
         cwd: /tmp/pip-install-_pzkjq73/mysql_02f1e1ca9632450ea6329469549864cf/
    Complete output (26 lines):
    running egg_info
    creating /tmp/pip-pip-egg-info-6lw2mkwl/mysql.egg-info
    writing /tmp/pip-pip-egg-info-6lw2mkwl/mysql.egg-info/PKG-INFO
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-_pzkjq73/mysql_02f1e1ca9632450ea6329469549864cf/setup.py", line 28, in <module>
        setup(
      File "/usr/local/lib/python3.9/site-packages/setuptools/__init__.py", line 153, in setup
        return distutils.core.setup(**attrs)
      File "/usr/local/lib/python3.9/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/local/lib/python3.9/distutils/dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "/usr/local/lib/python3.9/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/usr/local/lib/python3.9/site-packages/setuptools/command/egg_info.py", line 292, in run
        writer(self, ep.name, os.path.join(self.egg_info, ep.name))
      File "/usr/local/lib/python3.9/site-packages/setuptools/command/egg_info.py", line 628, in write_pkg_info
        metadata.write_pkg_info(cmd.egg_info)
      File "/usr/local/lib/python3.9/distutils/dist.py", line 1117, in write_pkg_info
        self.write_pkg_file(pkg_info)
      File "/usr/local/lib/python3.9/site-packages/setuptools/dist.py", line 172, in write_pkg_file
        license = rfc822_escape(self.get_license())
      File "/usr/local/lib/python3.9/distutils/util.py", line 476, in rfc822_escape
        lines = header.split('\n')
    AttributeError: 'list' object has no attribute 'split'
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/06/ef/c4efbf2a51fb46aba9be03a973638d9539c9ca10a5259b2cbb1a66133b2e/mysql-0.0.1.tar.gz#sha256=ca87a58c42b6588bafc76f3f5402073b595fc0f5cf1d027af38662bb9932f49f (from https://pypi.org/simple/mysql/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Could not find a version that satisfies the requirement mysql (from versions: 0.0.1, 0.0.2)
ERROR: No matching distribution found for mysql
ERROR: Service 'web' failed to build: The command '/bin/sh -c pip install mysql' returned a non-zero code: 1

Can any one help to resolve my issue?

**Comment by shmaxi** [comment]
@gopalkotlanka Having the same issue all of a sudden with installing the package.
I know for certain that on the 12th of May it was still intact.

Any leads to the problem someone?

**Comment by valhallasw** [comment]
First off, *don't use this package*. Use the actual package `mysqlclient` instead.

I've pushed a change that may (or may not) fix the issue. It looks like `distutils` has started to parse the license headers, which failed on the format used in this setup.py. Feel free to retest.
